#!/bin/bash
echo "🔥 Building Kids Levels..."

# Level 3 - If/Else: إشارة المرور
cat > levels/level3-kids.html << 'EOF'
<!DOCTYPE html><html lang="ar" dir="rtl"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Level 3: إشارة المرور الذكية</title><link rel="stylesheet" href="../css/cyber-theme.css"><style>.game-area{display:flex;flex-wrap:wrap;gap:20px;justify-content:center;margin:30px 0}.traffic-light{background:#111;padding:20px;border-radius:20px;display:flex;flex-direction:column;gap:15px;align-items:center}.light{width:80px;height:80px;border-radius:50%;background:#333;cursor:pointer;transition:all 0.3s}.light.red.active{background:red;box-shadow:0 0 30px red}.light.green.active{background:#0f0;box-shadow:0 0 30px #0f0}.code-area{background:#000;color:#0f0;padding:20px;border-radius:10px;font-family:monospace;font-size:1.2rem;min-width:300px}.success-popup{position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);background:#0f0;color:#000;padding:40px;border-radius:20px;text-align:center;z-index:1000;font-size:2rem}</style></head><body><canvas id="matrix-canvas"></canvas><div class="cyber-container"><header class="cyber-header"><h1 class="cyber-logo">🚦 LEVEL 3</h1><p class="cyber-subtitle">إشارة المرور الذكية - If/Else</p></header><div class="cyber-section"><h2 style="color:#ff4444;text-align:center">🚨 جدار ناري ذكي!</h2><p style="text-align:center;font-size:1.2rem">🤖 <strong>Agent Zero:</strong> "الجدار الناري يغير لونه!<br>إذا <span style="color:red">أحمر</span> = توقف! إذا <span style="color:#0f0">أخضر</span> = ادخل!"</p></div><div class="cyber-section"><h2 style="text-align:center">🎮 اضغط الإشارة الصحيحة</h2><div class="game-area"><div class="traffic-light"><div class="light red" id="red-light"></div><div class="light green" id="green-light"></div></div><div class="code-area" id="code-display"><pre>if light == "red":
    print("⛔ توقف!")
else:
    print("✅ ادخل!")</pre></div></div><p style="text-align:center;color:#ffd700" id="instruction">السؤال: النور أحمر... ماذا تفعل؟</p></div><div class="cyber-section" id="mission-complete" style="display:none;text-align:center"><div style="font-size:5rem">🏆</div><h2 style="color:#ffd700">فهمت If/Else!</h2><p>If = إذا الشرط صحيح → نفذ<br>Else = وإلا → نفذ شيء آخر</p><button class="cyber-btn primary" onclick="nextLevel(4)">➡️ المستوى التالي</button></div><div style="text-align:center;margin:30px 0"><a href="../index.html" class="cyber-btn">⬅️ العودة للخريطة</a></div></div><script>let score=0;let questions=[{light:"red",correct:"red",msg:"⛔ النور أحمر! توقف!"},{light:"green",correct:"green",msg:"✅ النور أخضر! ادخل!"},{light:"red",correct:"red",msg:"⛔ توقف!"}];let current=0;function showQuestion(){if(current>=questions.length){document.getElementById('mission-complete').style.display='block';if(window.SaveSystem)SaveSystem.save(3,{xp:100});return}let q=questions[current];document.getElementById('instruction').textContent='السؤال: النور '+q.light+'... ماذا تفعل؟'}document.getElementById('red-light').addEventListener('click',()=>{let q=questions[current];if(q.correct==='red'){score++;document.getElementById('red-light').classList.add('active');setTimeout(()=>{document.getElementById('red-light').classList.remove('active');current++;showQuestion()},1000)}else{document.getElementById('instruction').textContent='❌ خطأ! النور '+q.light+'... حاول مرة!'}});document.getElementById('green-light').addEventListener('click',()=>{let q=questions[current];if(q.correct==='green'){score++;document.getElementById('green-light').classList.add('active');setTimeout(()=>{document.getElementById('green-light').classList.remove('active');current++;showQuestion()},1000)}else{document.getElementById('instruction').textContent='❌ خطأ! النور '+q.light+'... حاول مرة!'}});showQuestion();function nextLevel(n){localStorage.setItem('cyberRPG_level',n);window.location.href='level'+n+'.html'}</script><script src="../js/save-system.js"></script></body></html>
EOF
echo "✅ Level 3 Kids created"

# Level 4 - Loops: فك الشفرة المتكررة
cat > levels/level4-kids.html << 'EOF'
<!DOCTYPE html><html lang="ar" dir="rtl"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Level 4: دوامة التكرار</title><link rel="stylesheet" href="../css/cyber-theme.css"><style>.loop-circle{width:200px;height:200px;border-radius:50%;border:5px solid #00ff41;display:flex;align-items:center;justify-content:center;margin:30px auto;animation:spin 3s linear infinite;font-size:3rem}@keyframes spin{0%{transform:rotate(0deg)}100%{transform:rotate(360deg)}}.code-steps{background:#000;color:#0f0;padding:20px;border-radius:10px;font-family:monospace;text-align:center;font-size:1.3rem;line-height:2}.counter{font-size:5rem;color:#ffd700;text-align:center;animation:pulse 1s infinite}@keyframes pulse{0%,100%{opacity:1}50%{opacity:0.5}}</style></head><body><canvas id="matrix-canvas"></canvas><div class="cyber-container"><header class="cyber-header"><h1 class="cyber-logo">🔄 LEVEL 4</h1><p class="cyber-subtitle">دوامة التكرار - For Loops</p></header><div class="cyber-section"><h2 style="color:#ff4444;text-align:center">🔐 كلمة السر متكررة!</h2><p style="text-align:center;font-size:1.2rem">🤖 <strong>Agent Zero:</strong> "الكود يتكرر 5 مرات!<br>كل تكرار = رقم سري جديد!"</p></div><div class="cyber-section"><h2 style="text-align:center">🎮 شاهد التكرار</h2><div class="loop-circle">🔄</div><div class="code-steps"><pre>for i in range(5):
    print("🔑 رقم سري:", i)</pre></div><div class="counter" id="counter">0</div><p style="text-align:center;color:#ffd700">التكرار رقم: <span id="loop-num">0</span> من 5</p><button class="cyber-btn" id="start-loop" style="display:block;margin:20px auto">▶️ ابدأ التكرار</button></div><div class="cyber-section" id="mission-complete" style="display:none;text-align:center"><div style="font-size:5rem">🏆</div><h2 style="color:#ffd700">فهمت Loops!</h2><p>For Loop = كرر الشيء عدد معين من المرات!</p><button class="cyber-btn primary" onclick="nextLevel(5)">➡️ المستوى التالي</button></div><div style="text-align:center;margin:30px 0"><a href="../index.html" class="cyber-btn">⬅️ العودة للخريطة</a></div></div><script>let count=0;document.getElementById('start-loop').addEventListener('click',function(){this.disabled=true;let interval=setInterval(()=>{count++;document.getElementById('counter').textContent=count;document.getElementById('loop-num').textContent=count;if(count>=5){clearInterval(interval);document.getElementById('mission-complete').style.display='block';if(window.SaveSystem)SaveSystem.save(4,{xp:100})}},1000)});function nextLevel(n){localStorage.setItem('cyberRPG_level',n);window.location.href='level'+n+'.html'}</script><script src="../js/save-system.js"></script></body></html>
EOF
echo "✅ Level 4 Kids created"

# Level 5 - Functions: روبوت مساعد
cat > levels/level5-kids.html << 'EOF'
<!DOCTYPE html><html lang="ar" dir="rtl"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Level 5: الروبوت المساعد</title><link rel="stylesheet" href="../css/cyber-theme.css"><style>.robot-parts{display:flex;flex-wrap:wrap;gap:15px;justify-content:center;margin:20px 0}.part{background:rgba(0,0,0,0.5);border:2px solid #00ff41;border-radius:15px;padding:20px;cursor:pointer;transition:all 0.3s;text-align:center;font-size:2rem}.part:hover{border-color:#ffd700;transform:scale(1.1)}.part.collected{background:rgba(0,255,65,0.3);border-color:#ffd700}.robot-display{text-align:center;font-size:5rem;margin:20px 0}</style></head><body><canvas id="matrix-canvas"></canvas><div class="cyber-container"><header class="cyber-header"><h1 class="cyber-logo">🤖 LEVEL 5</h1><p class="cyber-subtitle">الروبوت المساعد - Functions</p></header><div class="cyber-section"><h2 style="color:#ff4444;text-align:center">🧩 ابنِ روبوتك!</h2><p style="text-align:center;font-size:1.2rem">🤖 <strong>Agent Zero:</strong> "الدالة = روبوت صغير!<br>تجمع القطع = تبني الروبوت!"</p></div><div class="cyber-section"><h2 style="text-align:center">🎮 اجمع قطع الروبوت</h2><div class="robot-display" id="robot-display">⬜⬜⬜</div><div class="robot-parts"><div class="part" data-part="head">🗣️ رأس</div><div class="part" data-part="body">💪 جسم</div><div class="part" data-part="legs">🦿 أرجل</div></div><div class="code-steps" style="background:#000;color:#0f0;padding:20px;border-radius:10px;font-family:monospace;text-align:center;margin-top:20px"><pre>def build_robot():
    head = "🗣️"
    body = "💪"
    legs = "🦿"
    return head + body + legs</pre></div></div><div class="cyber-section" id="mission-complete" style="display:none;text-align:center"><div style="font-size:5rem">🤖</div><h2 style="color:#ffd700">بنيت روبوتك!</h2><p>Function = مجموعة أوامر لها اسم!</p><button class="cyber-btn primary" onclick="nextLevel(6)">➡️ المستوى التالي: معركة PHANTOM</button></div><div style="text-align:center;margin:30px 0"><a href="../index.html" class="cyber-btn">⬅️ العودة للخريطة</a></div></div><script>let collected=[];document.querySelectorAll('.part').forEach(part=>{part.addEventListener('click',function(){if(!collected.includes(this.dataset.part)){collected.push(this.dataset.part);this.classList.add('collected');document.getElementById('robot-display').textContent=collected.map(p=>({head:'🗣️',body:'💪',legs:'🦿'})[p]).join('');if(collected.length===3){document.getElementById('mission-complete').style.display='block';if(window.SaveSystem)SaveSystem.save(5,{xp:100})}}})});function nextLevel(n){localStorage.setItem('cyberRPG_level',n);window.location.href='level'+n+'.html'}</script><script src="../js/save-system.js"></script></body></html>
EOF
echo "✅ Level 5 Kids created"

echo "🎉 All Kids Levels (3,4,5) created!"
